name: meta_weather_api
description: A new Flutter package project.
version: 0.0.1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  json_annotation: ^4.0.0
  http: ^0.13.0

dev_dependencies:
  build_runner: ^2.1.1
  json_serializable: ^5.0.0
  coverage: ^1.0.3
  test: ^1.16.4
  mocktail: ^0.1.0

